version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 3000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  backend:
    build: .
    depends_on:
      - database
  database:
    image: mongo
    volumes:
      - mongo-db:/data/db
  
  auth:
    image: redis

volumes:
  mongo-db: