version: "3"
services:
  backend:
    build:
      args:
        NODE_ENV: development
    env_file:
      - ./.env
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev

  database:
    env_file:
      - ./.env
  
  auth:
    env_file:
      - ./.env
    