version: "3"
services:
  backend:
    build: 
      context: .
      args:
        NODE_ENV: development
    env_file:
      - ./.env
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
  database:
      image: mongo
      container_name: database-blog
      volumes:
        - mongo-db:/data/db
      env_file:
      - ./.env

volumes:
    mongo-db: