version: "3"
services:
    backend:
        build: .
        image: backend-image
        container_name: backend-blog
        ports:
          - 3000:3000
        environment:
          - PORT=3000
    database:
        image: mongo
        container_name: database-blog
        environment:
          - MONGO_INITDB_ROOT_USERNAME=pqtrng
          - MONGO_INITDB_ROOT_PASSWORD=devpassword 
        volumes:
          - mongo-db:/data/db

volumes:
    mongo-db: