version: "3"
services:
  nginx:
    ports:
      - 3000:80
  backend:
    build:
      args:
        NODE_ENV: development
    env_file:
      - ./.env
    volumes:
      - ./:/app
      - /app/node_modules
      - ./nginx/nginx-error.log:/var/log/nginx/error.log
    command: npm run dev

  database:
    env_file:
      - ./.env
    