module.exports = {
  DATABASE_NAME: process.env.DATABASE_NAME,
  DATABASE_IP: process.env.DATABASE_IP,
  DATABASE_PORT: process.env.DATABASE_PORT,
  DATABASE_USER: process.env.DATABASE_USER,
  DATABASE_PASSWORD: process.env.DATABASE_PASSWORD,
  AUTH_URL: process.env.AUTH_URL,
  AUTH_PORT: process.env.AUTH_PORT,
  SESSION_SECRET: process.env.AUTH_SESSION_SECRET,
};
